import Head from "next/head";
import Image from "next/image";
import LeftSidebar from "../components/LeftSidebar";
import Navbar from "../components/Navbar";
import styles from "../styles/Home.module.css";
import Hero from "../components/Hero.js";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex">
        {/* Left Side */}
        <LeftSidebar />
        {/* Middle Side */}
        <div className="flex-1">
          {/* Navbar */}
          <Hero />
          {/* Songs */}
          {/* MusicPlayer */}
        </div>

        {/* Right Side */}
      </div>
    </div>
  );
}
